module.exports = {
  apps: [
    {
      name: 'wa-saas-app',
      script: 'server.js',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      env_file: '.env',
      watch: false,
      max_memory_restart: '1G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: 'logs/pm2-error.log',
      out_file: 'logs/pm2-out.log',
      merge_logs: true,
      autorestart: true,
      kill_timeout: 5000,
      listen_timeout: 3000,
    },
    {
      name: 'wa-saas-cron',
      script: 'jobs/cron.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production' },
      env_file: '.env',
      watch: false,
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: 'logs/cron-error.log',
      out_file: 'logs/cron-out.log',
      autorestart: true,
      cron_restart: '0 */6 * * *',
    },
  ],
};
